# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Deploy
      uses: wangyucode/sftp-upload-action@v1.4.8
      with:
        host: ${{ secrets.SSH_URL }}
        username: github
        privateKey: ${{ secrets.PI4_GH_PRIVATE_KEY }}
        forceUpload: true
        localDir: './dist'
        remoteDir: '/var/www/gloomhaven-scenario-tree'
        port: 22
        dryRun: false
